version: '3'

services:
  dev-db:
    image: postgres:latest
    environment:
      POSTGRES_USER: soberb
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: nestTest
    ports:
      - '5434:5432'
    networks:
      - mynetwork
    volumes:
      - postgres_data:/var/lib/postgresql/data

networks:
  mynetwork:

volumes:
  postgres_data:
